//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiDemo
{
    using System;
    using System.Collections.Generic;
    
    public class Note
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Note1 { get; set; }
      //  public Nullable<System.DateTime> CreatedOn { get; set; }
        public string isDeleted { get; set; }
    }
}
